---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data=read.csv("/Users/marcusthuillier/Desktop/Rugby/Excel/6Nations.csv", header=T)
prob <- as.matrix(data[c(1,2,3,4,5,6),c(5,7,8,9,10,11,12)])
```

```{r}

#INITIALIZE 6 Nations

returns = rnorm(1:1000, mean = 0, sd = 1)

X = matrix(ncol = 15,nrow = 10000)
for (match in 1:15) {
  for (i in 1:10000) {
    X[i,match] = sample(returns,1)
  }
}

I = matrix(ncol = 15,nrow = 1)
I[1,1] = as.numeric(prob[1,3]) 
I[1,2] = as.numeric(prob[1,4]) 
I[1,3] = as.numeric(prob[1,5]) 
I[1,4] = as.numeric(prob[1,6])
I[1,5] = as.numeric(prob[1,7])
I[1,6] = as.numeric(prob[2,4]) 
I[1,7] = as.numeric(prob[2,5])  
I[1,8] = as.numeric(prob[2,6]) 
I[1,9] = as.numeric(prob[2,7]) 
I[1,10] = as.numeric(prob[3,5]) 
I[1,11] = as.numeric(prob[3,6])
I[1,12] = as.numeric(prob[3,7])
I[1,13] = as.numeric(prob[4,6])
I[1,14] = as.numeric(prob[4,7])
I[1,15] = as.numeric(prob[5,7])

R = matrix(ncol = 15,nrow = 10000)

colnames(R) <- c("Ire-Wal","Ire-Eng","Ire-Sco","Ire-Fra","Ire-Ita",
                 "Wal-Eng","Wal-Sco","Wal-Fra","Wal-Ita",
                 "Eng-Sco","Eng-Fra","Eng-Ita",
                 "Sco-Fra","Sco-Ita",
                 "Fra-Ita")
for (index in 1:15) {
  for (i in 1:10000) {
    if (X[i,index] < qnorm(I[1,index])) {
      R[i,index] = strsplit(colnames(R)[index],"-")[[1]][1]
    }
    else if (X[i,index] > qnorm(I[1,index])) {
      R[i,index] = strsplit(colnames(R)[index],"-")[[1]][2]
    }
    else if (X[i,index] == qnorm(I[1,index])) {
      R[i,index] = "Draw"
    }
  }
}

```

```{r}

# GROUP A VICTORIES
library(stringr)
group <- matrix(ncol = 6,nrow = 10000)
colnames(group) <- c("Ire","Wal","Eng","Sco","Fra","Ita")
for (i in 1:10000) {
  group[i,1] = sum(str_count(R[i,], "Ire"))
  group[i,2] = sum(str_count(R[i,], "Wal"))
  group[i,3] = sum(str_count(R[i,], "Eng"))
  group[i,4] = sum(str_count(R[i,], "Sco"))
  group[i,5] = sum(str_count(R[i,], "Fra"))
  group[i,6] = sum(str_count(R[i,], "Ita"))
}

```

```{r}
# AVG VICTORIES

mean(group[,1])
mean(group[,2])
mean(group[,3])
mean(group[,4])
mean(group[,5])
mean(group[,6])

```

```{r}

rank <- matrix(ncol = 6,nrow = 10000)

for (i in 1:10000) {
  rank[i,1] = rank(group[i,], ties.method= "random")[1]
  rank[i,2] = rank(group[i,], ties.method= "random")[2]
  rank[i,3] = rank(group[i,], ties.method= "random")[3]
  rank[i,4] = rank(group[i,], ties.method= "random")[4]
  rank[i,5] = rank(group[i,], ties.method= "random")[5]
  rank[i,6] = rank(group[i,], ties.method= "random")[6]
}

#Ireland
a1 <- c(sum(rank[,1] == 6)/10000,sum(rank[,1] == 5)/10000,sum(rank[,1] == 4)/10000,sum(rank[,1] == 3)/10000,sum(rank[,1] == 2)/10000,sum(rank[,1] == 1)/10000)
#Wales
a2 <- c(sum(rank[,2] == 6)/10000,sum(rank[,2] == 5)/10000,sum(rank[,2] == 4)/10000,sum(rank[,2] == 3)/10000,sum(rank[,2] == 2)/10000,sum(rank[,2] == 1)/10000)
#England
a3 <- c(sum(rank[,3] == 6)/10000,sum(rank[,3] == 5)/10000,sum(rank[,3] == 4)/10000,sum(rank[,3] == 3)/10000,sum(rank[,3] == 2)/10000,sum(rank[,3] == 1)/10000)
#Scotland
a4 <- c(sum(rank[,4] == 6)/10000,sum(rank[,4] == 5)/10000,sum(rank[,4] == 4)/10000,sum(rank[,4] == 3)/10000,sum(rank[,4] == 2)/10000,sum(rank[,4] == 1)/10000)
#France
a5 <- c(sum(rank[,5] == 6)/10000,sum(rank[,5] == 5)/10000,sum(rank[,5] == 4)/10000,sum(rank[,5] == 3)/10000,sum(rank[,5] == 2)/10000,sum(rank[,5] == 1)/10000)
#Italy
a6 <- c(sum(rank[,6] == 6)/10000,sum(rank[,6] == 5)/10000,sum(rank[,6] == 4)/10000,sum(rank[,6] == 3)/10000,sum(rank[,6] == 2)/10000,sum(rank[,6] == 1)/10000)


final <- data.frame("Ireland" = a1, "Wales" = a2, "England" = a3, "Scotland" = a4, "France" = a5, "Italy" = a6)
final

```



